### ISSUE TITLE
Grafana annotation has empty data section

### ISSUE THREAD

**Issue by smcquay** [wish/eventmaster#48]
renders as:

```
Data: map[]
```

As it turns out the function that fetches collections of events [hard-codes "should I fetch data" to `false`](https://github.com/ContextLogic/eventmaster/blob/master/cassandra.go#L322).

We need to decide if the cost of always fetching data is fine; if `false` is changed to `true` the data shows up in Grafana.

**Comment by zxia-wish** [comment]
Fixed
